### PR TITLE
test: use dynamic import

### LINKED ISSUE #2: test: rewrite test.sh with TypeScript
from https://github.com/WillBooster/gen-i18n-ts/pull/1#discussion_r406161807

### LINKED ISSUE #78: fix(test): yarn lint fails before running test
`temp` directory does not exist. It's inconvenient...
We need to search how to manage a software for code generation.

### PR DESCRIPTION
**Pull request by kumachan-mis**
close #2
close #78

### CODE REVIEW

File: __tests__/i18n-1.ts [hunk 1]
```diff
@@ -1,8 +1,18 @@
...
 
 test('i18n-1: simple website', async () => {
+  const inputDir = path.resolve(__dirname, '..', 'test-fixtures', 'i18n-1');
+  const outFile = path.resolve(__dirname, '..', 'test-fixtures', 'temp', 'i18n-1.ts');
+  genI18ts(inputDir, outFile, 'en');
+
+  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
+  // @ts-ignore: Auto-generated module
+  // eslint-disable-next-line import/no-unresolved
+  const { i18n, changeCurrentLang } = await import('../test-fixtures/temp/i18n-1');
```
Comment (exKAZUu) [inline __tests__/i18n-1.ts:14]: I think we should use `require` function.

File: __tests__/i18n-1.ts [hunk 2]
```diff
@@ -1,8 +1,19 @@
...
 
 test('i18n-1: simple website', async () => {
+  const inputDir = path.resolve(__dirname, '..', 'test-fixtures', 'i18n-1');
+  const outFile = path.resolve(__dirname, '..', 'test-fixtures', 'i18n-1.ts');
+  genI18ts(inputDir, outFile, 'en');
+
+  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
+  // @ts-ignore: Auto-generated module
+  // eslint-disable-next-line import/no-unresolved
+  const { i18n, changeCurrentLang } = await require('../test-fixtures/i18n-1');
```
Comment (exKAZUu) [inline __tests__/i18n-1.ts:15]: Please remove `await` because `require` doesn't return `Promise`

**Review by exKAZUu — APPROVED** [review]
LGTM :+1:
